import PDFDocument from "pdfkit";

// Genera un PDF de "evidencia satelital" a partir de los datos de un campo.
// El contenido es determinista para poder testearlo renderizando a buffer.

const T = {
  es: {
    title: "Reporte de evidencia satelital",
    farm: "Campo", country: "País", coord: "Coordenadas", area: "Superficie",
    elev: "Elevación", generated: "Generado", pass: "Pasada satelital: Sentinel-2 (demo)",
    riskSummary: "Resumen de riesgo del campo", zonesTitle: "Zonas de manejo",
    zone: "Zona", crop: "Cultivo", ndvi: "NDVI", fire: "Incendio", soil: "Humedad",
    risks: { fire: "Incendio", drought: "Sequía", flood: "Inundación", pest: "Plagas", frost: "Helada", wind: "Viento" },
    footer: "Documento generado por Vigia. Coordenadas y hora de pasada satelital incluidas para fines de seguro.",
  },
  en: {
    title: "Satellite evidence report",
    farm: "Farm", country: "Country", coord: "Coordinates", area: "Area",
    elev: "Elevation", generated: "Generated", pass: "Satellite pass: Sentinel-2 (demo)",
    riskSummary: "Farm risk summary", zonesTitle: "Management zones",
    zone: "Zone", crop: "Crop", ndvi: "NDVI", fire: "Fire", soil: "Moisture",
    risks: { fire: "Wildfire", drought: "Drought", flood: "Flood", pest: "Pests", frost: "Frost", wind: "Wind" },
    footer: "Document generated by Vigia. Coordinates and satellite pass time included for insurance purposes.",
  },
  pt: {
    title: "Relatório de evidência de satélite",
    farm: "Campo", country: "País", coord: "Coordenadas", area: "Superfície",
    elev: "Elevação", generated: "Gerado", pass: "Passagem do satélite: Sentinel-2 (demo)",
    riskSummary: "Resumo de risco do campo", zonesTitle: "Zonas de manejo",
    zone: "Zona", crop: "Cultura", ndvi: "NDVI", fire: "Incêndio", soil: "Umidade",
    risks: { fire: "Incêndio", drought: "Seca", flood: "Inundação", pest: "Pragas", frost: "Geada", wind: "Vento" },
    footer: "Documento gerado pela Vigia. Coordenadas e hora da passagem do satélite incluídas para fins de seguro.",
  },
};

const GREEN = "#0E9F5B";
const INK = "#1a1a1a";
const MUTE = "#6b7280";

// Helvetica (WinAnsi) no incluye primas tipográficas; se normalizan.
export const clean = (s) => String(s ?? "—").replace(/[′’]/g, "'").replace(/[″”]/g, '"');

export function buildReportPdf(doc, data = {}) {
  const t = T[data.lang] || T.es;
  const farm = data.farm || {};
  const risks = data.risks || {};
  const zones = Array.isArray(data.zones) ? data.zones : [];
  const gen = data.generatedAt || "";

  // Encabezado
  doc.fillColor(GREEN).fontSize(22).font("Helvetica-Bold").text("Vigia", 40, 44);
  doc.fillColor(MUTE).fontSize(10).font("Helvetica").text("vigia.ag", 40, 70);
  doc.fillColor(INK).fontSize(15).font("Helvetica-Bold").text(t.title, 40, 96);
  doc.moveTo(40, 122).lineTo(555, 122).strokeColor("#e5e7eb").stroke();

  // Datos del campo
  let y = 138;
  const y0 = y;
  const col2 = (label, value, x) => {
    doc.fillColor(MUTE).fontSize(9).font("Helvetica").text(label.toUpperCase(), x, y0);
    doc.fillColor(INK).fontSize(12).font("Helvetica-Bold").text(String(value ?? "—"), x, y0 + 12);
  };
  col2(t.farm, `${farm.label || "—"}`, 40);
  col2(t.country, farm.country || "—", 320);
  y += 38;
  const y1 = y;
  doc.fillColor(MUTE).fontSize(9).font("Helvetica").text(t.coord.toUpperCase(), 40, y1);
  doc.fillColor(INK).fontSize(12).font("Helvetica-Bold").text(clean(farm.coord), 40, y1 + 12);
  doc.fillColor(MUTE).fontSize(9).font("Helvetica").text(t.area.toUpperCase(), 320, y1);
  doc.fillColor(INK).fontSize(12).font("Helvetica-Bold").text(farm.hectares != null ? `${farm.hectares} ha` : "—", 320, y1 + 12);
  y += 44;
  doc.fillColor(MUTE).fontSize(9).font("Helvetica")
    .text(`${t.generated}: ${gen}`, 40, y).text(t.pass, 40, y + 12);
  y += 40;

  // Resumen de riesgo
  doc.fillColor(INK).fontSize(13).font("Helvetica-Bold").text(t.riskSummary, 40, y);
  y += 22;
  const barW = 260;
  for (const key of ["fire", "drought", "flood", "pest", "frost", "wind"]) {
    const v = Math.max(0, Math.min(100, Number(risks[key]) || 0));
    doc.fillColor(INK).fontSize(10).font("Helvetica").text(t.risks[key], 40, y);
    doc.roundedRect(180, y + 1, barW, 8, 2).fillColor("#eef2f0").fill();
    doc.roundedRect(180, y + 1, (barW * v) / 100, 8, 2).fillColor(v >= 60 ? "#D14B33" : v >= 40 ? "#E88A2E" : GREEN).fill();
    doc.fillColor(INK).fontSize(10).font("Helvetica-Bold").text(`${v}%`, 180 + barW + 10, y);
    y += 20;
  }
  y += 12;

  // Tabla de zonas
  doc.fillColor(INK).fontSize(13).font("Helvetica-Bold").text(t.zonesTitle, 40, y);
  y += 20;
  const cols = [
    [t.zone, 40], [t.crop, 100], [t.ndvi, 300], ["ha", 370], [`${t.fire} %`, 430], [`${t.soil} %`, 500],
  ];
  doc.fillColor(MUTE).fontSize(9).font("Helvetica-Bold");
  for (const [label, x] of cols) doc.text(label.toUpperCase(), x, y);
  y += 14;
  doc.moveTo(40, y).lineTo(555, y).strokeColor("#e5e7eb").stroke();
  y += 6;
  doc.font("Helvetica").fontSize(10).fillColor(INK);
  for (const z of zones) {
    doc.fillColor(INK).text(String(z.id ?? "—"), 40, y);
    doc.text(String(z.crop ?? "—"), 100, y, { width: 190, ellipsis: true });
    doc.text(z.ndvi != null ? Number(z.ndvi).toFixed(2) : "—", 300, y);
    doc.text(String(z.ha ?? "—"), 370, y);
    doc.text(z.fire != null ? `${z.fire}%` : "—", 430, y);
    doc.text(z.soil != null ? `${z.soil}%` : "—", 500, y);
    y += 18;
  }

  // Pie
  doc.fillColor(MUTE).fontSize(8).font("Helvetica").text(t.footer, 40, 770, { width: 515 });
}

// Renderiza el PDF a un Buffer (para tests).
export function renderReportToBuffer(data) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 40, size: "A4" });
    const chunks = [];
    doc.on("data", (c) => chunks.push(c));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);
    buildReportPdf(doc, data);
    doc.end();
  });
}
